source 'https://rubygems.org'

ruby '3.2.2'

gem 'rails', '~> 7.1.5'
gem 'mysql2'
gem 'puma'
gem 'bootsnap', require: false
gem 'redis'
gem 'sidekiq'
gem 'sneakers'

group :development, :test do
  gem 'debug'
end